### ISSUE TITLE
[Bug]: Storage recursive download does not preserve directories

### ISSUE THREAD

**Issue by sposs** [exoscale/cli#545] opened 2023-09-27 11:08 UTC
### Current Behavior

Executing
```
exo storage download sos://BUCKET/somepath/ ./ -r -f 
```
creates all sub directories as empty files, for example, if there is a file `sos://BUCKET/somepath/subpath/file`, the resulting directory will contain the files `somepath` and `subpath`, both empty and not directories, as well as the expected `file`.  

### Expected Behavior

The recursive download must preserve the directory structure. The recursive download
```
exo storage download sos://BUCKET/somepath/ ./ -r -f 
```
containing `subpath/file` should yield locally the directory structure `somepath/subpath/file`.

### Steps To Reproduce

Execute `exo storage download sos://BUCKET/somepath/ ./ -r -f` where `somepath` contains sub directories

### CLI Version

exo 1.73.0 968fc649 (egoscale 0.101.0)

### Os platform

debian 12

**Comment by sauterp** [comment] 2023-09-28 13:26
Hi,
I'm unable to reproduce what you describe with the exact same version of exo cli. Here's what I did in detail:
```shell
# create a bucket
❯ exo storage mb mybucket

# upload files in a subdirectory
❯ mkdir upload

❯ cd upload

❯ mkdir -p somepath/subpath

❯ echo asdf  > somepath/subpath/file

❯ exo storage upload -r ./ mybucket
somepath/subpat… [==============================================================================] 5.00 b / 5.00 b | 0s

❯ exo storage list -z ch-dk-2 -r mybucket
2023-09-28 12:48:40 UTC    5 B  somepath/subpath/file

❯ cd ..

❯ mkdir downloads

❯ cd downloads

❯ exo storage download sos://mybucket/somepath/ ./ -r -f
somepath/subpat… [==============================================================================] 5.00 b / 5.00 b | 0s

❯ tree
.
└── subpath
    └── file

2 directories, 1 file

❯ cat subpath/file
asdf
```
This is the expected behaviour.

It sounds like you also want the `somepath` directory, in that case you need to run the command without the subprefix
```shell
❯ cd ..

❯ mkdir nosubprefix

❯ cd nosubprefix/

❯ exo storage download sos://mybucket ./ -r -f
somepath/subpat… [==============================================================================] 5.00 b / 5.00 b | 0s

❯ tree
.
└── somepath
    └── subpath
        └── file

3 directories, 1 file

❯ cat somepath/subpath/file
asdf
```

**Comment by sposs** [comment] 2023-09-28 16:19
I think the issue is not in exoscale. In fact I use s3fs to store the files. I saw that a json listing of the bucket contains e.g. `{"name":"AIC/ASC/","size":0,"last_modified":"2022-10-22 15:13:37 UTC","dir":false,"version_id":null,"version_number":null}`. Note the `"dir":false` part. This is the cause I think of the issue.

**Comment by sauterp** [comment] 2023-09-28 17:11
OK, I'm closing this issue then.

**Closed by sauterp** 2023-09-28 17:11 UTC
Labels: bug

**Comment by sposs** [comment] 2023-09-29 05:54
Actually, the issue I have now is that exoscale advertises the use of s3fs, but clearly the metadata stored is incorrect. I understand that it's not the exo cli's responsibility, but nevertheless could you ensure this issue is propagated to the documentation?

**Comment by sauterp** [comment] 2023-09-29 08:16
I checked the documentation about the [limitations of s3fs](https://fs-s3fs.readthedocs.io/en/latest/#limitations) and found this "if you create a file called “foo/bar”, S3FS will create an S3 object for the file called “foo/bar” and an empty object called “foo/” which stores that fact that the “foo” directory exists.". It looks to me like this is exactly what you are seeing. This means that the representation of your data by s3fs in SOS is not intended for use without s3fs. Hence if you download your data with an S3 client like `exo` or any other client, you will not get your data in the original format you stored it on your disk. It seems you can only use the data from a bucket created with s3fs, with s3fs itself.

If you suspect that something may be wrong on SOS's side, please provide us with more details, so we can investigate and if you don't feel comfortable sharing this information here in public, you can also reach us through the 'Support' section in our [Portal](https://portal.exoscale.com).

**Comment by sposs** [comment] 2023-09-29 08:32
Ok, so the issue is in s3fs, as suspected. I guess the exoscale doc should mention as a warning that the data stored with s3fs is not meant to be obtained with other tools than s3fs... 
I've written my own downloader based on the json dump, using the exo cli (great tool!). All good for me now. 
Thanks.
