### ISSUE TITLE
Invalid Authorization header (exo runstatus list)

### ISSUE THREAD

**Issue by SebastienPittet** [exoscale/cli#296] opened 2020-11-11 11:29 UTC
Hello !

I tried to update a RunStatus page with the CLI and it triggered the error message **"Invalid Authorization header"**.

- Version : exo 1.20.0 a6a1cb0 (egoscale 0.33.2)
- OS : Debian (but... running on Windows Subsystem for Linux).

Did you also have the same error ?

**Comment by falzm** [comment] 2020-11-12 08:03
Duplicate of https://github.com/exoscale/cli/issues/288.

**Closed by falzm** 2020-11-12 08:03 UTC
