### ISSUE TITLE
interactive config does read using Powershell

### ISSUE THREAD

**Issue by greut** [exoscale/cli#37] opened 2018-10-31 06:54 UTC
The first selection appears, then the question doesn't. 

![askquestion](https://user-images.githubusercontent.com/1388/47771060-194d0e00-dce2-11e8-9579-9b086cadcf0c.png)

Sending y or N goes further though.

**Comment by pierre-emmanuelJ** [comment] 2018-11-01 08:43
oh thank you! I don't know if this lib ()selector work well with Windows? 
I will check that 👍

**Comment by falzm** [comment] 2021-04-09 06:59
Can't reproduce, closing for now.

**Closed by falzm** 2021-04-09 06:59 UTC
Labels: bug
